<?php
if( function_exists('register_field_group') )
{
	register_field_group(array (
		'key' => 'group_54b56e1f58d05',
		'title' => 'Grant Fields',
		'fields' => array (
			array (
				'key' => 'field_54b56e311b37f',
				'label' => 'Amount',
				'name' => 'grant_amount',
				'prefix' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_54b56e791b380',
				'label' => 'Term Start',
				'name' => 'grant_term_start',
				'prefix' => '',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'm/d/Y',
				'return_format' => 'm/d/Y',
				'first_day' => 0,
			),
			array (
				'key' => 'field_54b56eb41b381',
				'label' => 'Term End',
				'name' => 'grant_term_end',
				'prefix' => '',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'm/d/Y',
				'return_format' => 'm/d/Y',
				'first_day' => 0,
			),
			array (
				'key' => 'field_54b56ecb1b382',
				'label' => 'Description',
				'name' => 'description',
				'prefix' => '',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'br',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_54b56f1a1b383',
				'label' => 'Related Topics',
				'name' => 'grant_topics',
				'prefix' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array (
					0 => 'topic',
				),
				'taxonomy' => '',
				'filters' => array (
					0 => 'post_type',
				),
				'elements' => '',
				'max' => '',
				'return_format' => 'object',
			),
			array (
				'key' => 'field_54b56f3b1b384',
				'label' => 'Related Initiatives',
				'name' => 'grant_initiatives',
				'prefix' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array (
					0 => 'initiative',
				),
				'taxonomy' => '',
				'filters' => array (
					0 => 'post_type',
				),
				'elements' => '',
				'max' => '',
				'return_format' => 'object',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'grant',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));
}